Model documentation updated, boundary reaction section
opencobra/cobrapy pull request #1039
Opened 2021-02-09 12:44 UTC by matthiaskoenig

* [x] fix #1038
* [x] description of feature/fix
* [x] tests added/passed
* [x] add an entry to the [next release](../release-notes/next-release.md)

I updated the section model building in the documentation. I could not find any information on how to update the docs so just updated the notebook. Please let me know what else is required.

2021-02-09 14:26 UTC, Midnighter requested changes
Thank you for dedicating time to the documentation! 😃 Unfortunately, reviewing changes in notebooks is still painful 🙁

* Committing the empty file ` test/exchange_reaction.py` seems like a mistake?
* I've added some suggestions for changes and additions.
* I think it would be great to also show the model attribute `boundary` because it is useful for iterating over all boundary reactions or ignoring them, for example,

    ```py
    set(model.reactions) - set(model.boundary)
    ```

    to get all 'real' reactions (including biomass).

2021-02-09 14:26 UTC, Midnighter commented on documentation_builder/building_model.ipynb
> +    "# Best practise: SBML compliant IDs\n",
Instead of a comment, I suggest turning this into a separate markdown cell with some more information on _what is_ an SBML compliant ID, for example, with a quote from the SBML specification.

2021-02-09 14:26 UTC, Midnighter commented on documentation_builder/building_model.ipynb
> +    "Boundary reactions can be added using the `add_boundary`.\n",
```suggestion
    "Boundary reactions can be added using the model's method `add_boundary`.\n",
```

2021-02-09 14:26 UTC, Midnighter commented on documentation_builder/building_model.ipynb
> +    "There are three different types of pre-defined boundary reactions: exchange, demand, and sink reactions. An exchange reaction is a reversible, unbalanced reaction that adds to or removes an extr
```suggestion
    "There are three different types of pre-defined boundary reactions: exchange, demand, and sink reactions. All of them are unbalanced pseudo reactions, that means they fulfill a function for modeling by adding to or removing metabolites from the model system but are not based on real biology. An exchange reaction is a reversible reaction that adds to or removes an extracellular metabolite from the extracellular compartment. A demand reaction is an irreversible reaction that consumes an intracellular metabolite. A sink is similar to an exchange but specifically for intracellular metabolites, i.e., a reversible reaction that adds or removes an intracellular metabolite."
```

2021-02-09 14:26 UTC, Midnighter commented on documentation_builder/building_model.ipynb
> +    "Boundary reactions are defined on metabolites. First we add two metabolites to the model than\n",
```suggestion
    "Boundary reactions are defined on metabolites. First we add two metabolites to the model then\n",
```

2021-02-09 14:26 UTC, Midnighter commented on documentation_builder/building_model.ipynb
> +    "we define the boundaries, glycogen in the `c` compartement and co2_e in the external compartment `e`."
```suggestion
    "we define the boundary reactions. We add glycogen to the cytosolic compartment `c` and CO2 to the external compartment `e`."
```

2021-02-09 14:26 UTC, Midnighter commented on release-notes/next-release.md
> +- documentation of exchange reactions (#1038)
```suggestion
- documentation of boundary reactions (#1038)
```

2021-02-09 19:17 UTC, cdiener commented
Looks like RTD is broken anyways. Last docs are from 0.17.0 and it seems the Github integration has been turned off.

2021-02-09 20:31 UTC, matthiaskoenig commented on documentation_builder/building_model.ipynb
> +    "# Best practise: SBML compliant IDs\n",
I added a corresponding side note. In addition I added a section about validation which allows to check the created model for COBRA and SBML errors/warnings. This belongs also in the model creation section.

2021-02-09 20:41 UTC, matthiaskoenig commented
@cdiener Yes, the RTD and github integration are important, but I can't fix these.

I have the impression we get a lot of basic/core questions on the google-group recently. These could all be solved by a bit better documentation of features in the docs.

 @Midnighter All requested changes have been done.

2021-02-10 09:29 UTC, Midnighter approved these changes
Great thanks! Yes, fixing the docs is important. (Although many of the recent questions made me suspect that even the existing documentation was not read.)

I think now that cobrapy is a pure Python package we could actually let RTD install the package which would alleviate some headache with auto-generating the API reference.

2021-02-10 09:29 UTC, merged