fix: issue #926
opencobra/cobrapy pull request #1055
Opened 2021-03-16 19:52 UTC by dtmvandenberg

* [x] fix #926 
* [x] description of feature/fix
* [x] tests added/passed
* [ ] add an entry to the [next release](../release-notes/next-release.md)

2021-03-16 20:48 UTC, cdiener requested changes
Hi, looks good. A small formatting change so it passes the pep8 checks. We require the code to be pep8-compliant. If you're using vscode or something you can usually activate flake8 checks which helps with that.

Also there is a `.swp` file that probably was not supposed to be added so this would need to be removed as well.

And finally, it would be great if you could add a test so this does not pop up again. For that you can add something along the lines of:

```python
def test_compartment_changes(model):
    rxn = model.reactions.EX_ac_e
    assert rxn.reactants[0].compartment in rxn.compartments
    rxn.reactants[0].compartment = "blub"
    assert rxn.reactants[0].compartment in rxn.compartments
```

to the end of `src/cobra/test/test_core/test_core_reaction.py`.

2021-03-16 20:48 UTC, cdiener commented on src/cobra/core/reaction.py
>              }
Formatting is a bit off.

```suggestion
        return {
            met.compartment
            for met in self._metabolites
            if met.compartment is not None
        }
```

2021-03-17 16:06 UTC, dtmvandenberg commented
@cdiener I changed the files you requested and i commited them but Github will not update so I am stuck...

2021-03-17 16:40 UTC, cdiener requested changes
:+1:

2021-03-17 16:40 UTC, cdiener commented on src/cobra/core/reaction.py
> +        }
Sorry, my bad. This is what the formatter wants now.

```suggestion
        return {
            met.compartment for met in self._metabolites if met.compartment is not None
        }
```

2021-03-17 18:36 UTC, cdiener requested changes
Some of the old commits crept back in it seems (the `.swp` file is back as well). Pretty close though.

2021-03-17 18:36 UTC, cdiener commented on .gitignore
> +.vscode/settings.json
Even `.vscode/*`.

2021-03-17 18:36 UTC, cdiener commented on src/cobra/core/reaction.py
> +        return {
This is the old formatting again.

2021-03-18 06:43 UTC, dtmvandenberg commented
@cdiener Everything should be okay now, sorry for the amount of work. Do you know how to initialize a new codecov report? Then everything should be in order for the merge.

2021-03-18 16:22 UTC, cdiener approved these changes
Looks good now. Thanks for contributing!

2021-03-18 18:11 UTC, merged