refactor: cobra.io.json
opencobra/cobrapy pull request #1151
Opened 2022-02-16 20:31 UTC by synchon

* [ ] fix #(issue number)
* [x] description of feature/fix
* [ ] tests added/passed
* [ ] add an entry to the [next release](../release-notes/next-release.md)

This PR adds typing annotations for cobra.io.json and its unit tests. It also upgrades the code style for them to maintain Python 3.6+ compatibility.

2022-02-16 20:32 UTC, synchon commented
To be merged after #1134 is merged.

2022-02-17 10:42 UTC, Midnighter approved these changes
👍🏼

2022-02-17 10:44 UTC, Midnighter requested changes
```
  src/cobra/__init__.py:17: in <module>
      from cobra import io
  src/cobra/io/__init__.py:5: in <module>
      from cobra.io.json import from_json, load_json_model, save_json_model, to_json
  src/cobra/io/json.py:5: in <module>
      from ..dict import model_from_dict, model_to_dict
  E   ModuleNotFoundError: No module named 'cobra.dict'
```

2022-02-17 10:44 UTC, Midnighter commented on src/cobra/io/json.py
> +from ..dict import model_from_dict, model_to_dict
```suggestion
from .dict import model_from_dict, model_to_dict
```

2022-02-17 11:29 UTC, synchon commented on src/cobra/io/json.py
> +from ..dict import model_from_dict, model_to_dict
Shoot! Missed it. Sending a fix now.

2022-02-17 11:44 UTC, synchon commented
Checks were taking some time, hence rebased it on latest devel.

2022-02-17 12:27 UTC, Midnighter approved these changes

2022-02-17 12:27 UTC, merged