Refactor/metabolite
opencobra/cobrapy pull request #1168
Opened 2022-03-07 00:26 UTC by akaviaLab

* [X] description of feature/fix
Refactor metabolite.py and test_metabolite.py to be Python 3.6+ compliant including
removing future, typing, removing bugbears, documentation

2022-03-07 09:50 UTC, Midnighter requested changes
Overall, it looks good. I'm in doubt about the `Any` again. Would have to look more thoroughly at the code myself to make a call. Which is also an option. I can add fix ups afterwards if you prefer.

2022-03-07 09:50 UTC, Midnighter commented on src/cobra/core/metabolite.py
> +        compartment: str = None,
Always make type annotations `Optional` when the argument can be `None`, please.

2022-03-07 09:50 UTC, Midnighter commented on src/cobra/core/metabolite.py
> +    ):
```suggestion
    ) -> None:
```

2022-03-07 09:50 UTC, Midnighter commented on src/cobra/core/metabolite.py
>          Species.__init__(self, id, name)
```suggestion
        super().__init__(id=id, name=name)
```

2022-03-07 09:50 UTC, Midnighter commented on src/cobra/core/metabolite.py
> +    def elements(self) -> Union[None, Dict[Any, Union[int, float]]]:
```suggestion
    def elements(self) -> Optional[Dict[str, Union[int, float]]]:
```

2022-03-07 09:50 UTC, Midnighter commented on src/cobra/core/metabolite.py
> +    def elements(self) -> Union[None, Dict[Any, Union[int, float]]]:
Or can it be something other than `str`?

2022-03-07 09:50 UTC, Midnighter commented on src/cobra/core/metabolite.py
> +                <td>{"0x0%x" % id(self)}</td>
```suggestion
                <td>{id(self):#x}</td>
```

2022-03-07 15:40 UTC, akaviaLab commented on src/cobra/core/metabolite.py
> +    def elements(self) -> Union[None, Dict[Any, Union[int, float]]]:
I think that metabolite is only str, but DictList (as defined) is more complicated. I'll go into detail why I used Any in dictlist in that PR.

2022-03-12 14:32 UTC, Midnighter approved these changes
LGTM

2022-03-12 14:32 UTC, Midnighter commented on src/cobra/core/metabolite.py
> +    def elements(self) -> Union[None, Dict[str, Union[int, float]]]:
```suggestion
    def elements(self) -> Optional[Dict[str, Union[int, float]]]:
```

2022-03-12 14:34 UTC, merged