Refactor/core dictlist2
opencobra/cobrapy pull request #1169
Opened 2022-03-07 01:15 UTC by akaviaLab

Refactor dictlist.py and test_dictlist.py to be Python 3.6+ compliant including type hints, f-strings, no utf-8, no future imports

2022-03-07 09:31 UTC, Midnighter requested changes
Thank you for updating the module. I'm unfortunately not too willing to allow too many `Any` annotations since that doesn't add helpful information. I think, in most cases the `Any` can be replaced with either `Object` or `Union[Object, str]`.

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +            raise TypeError(f"takes at most 1 argument ({len(args):d} given)")
The `:d` format specification is not strictly necessary, I think, but it also doesn't hurt.

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def has_id(self, id: Any) -> bool:
Pretty sure `id` has to be a string, no?
```suggestion
    def has_id(self, id: str) -> bool:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def has_id(self, id: Any) -> bool:
Or is it `Union[cobra.core.Object, str]`?

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def _check(self, id: Any) -> None:
Same question about `id`.

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def get_by_id(self, id: Any) -> Any:
Same, what is `id`'s type?

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +        def select_attribute(x: Union[type(None), Any]) -> Any:
```suggestion
        def select_attribute(x: Optional[Any]) -> Any:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def union(self, iterable: Iterable) -> None:
Is this too specific?

```suggestion
    def union(self, iterable: Iterable[Object]) -> None:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
>          if not hasattr(self, "_dict") or self._dict is None:
```suggestion
        if getattr(self, "_dict", None) is None:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def extend(self, iterable: Iterable) -> None:
I think

```suggestion
    def extend(self, iterable: Iterable[Object]) -> None:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def _extend_nocheck(self, iterable: Iterable) -> None:
```suggestion
    def _extend_nocheck(self, iterable: Iterable[Object]) -> None:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def __sub__(self, other: Iterable) -> "DictList":
```suggestion
    def __sub__(self, other: Iterable[Object]) -> "DictList":
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def __isub__(self, other: Iterable) -> "DictList":
```suggestion
    def __isub__(self, other: Iterable[Object]) -> "DictList":
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def __add__(self, other: Iterable) -> "DictList":
```suggestion
    def __add__(self, other: Iterable[Object]) -> "DictList":
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def __iadd__(self, other: Iterable) -> "DictList":
```suggestion
    def __iadd__(self, other: Iterable[Object]) -> "DictList":
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def __setstate__(self, state) -> None:
```suggestion
    def __setstate__(self, state: dict) -> None:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def insert(self, index, entity) -> None:
```suggestion
    def insert(self, index: int, entity: Object) -> None:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def pop(self, *args) -> Any:
```suggestion
    def pop(self, *args) -> Object:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def add(self, x: Any) -> None:
```suggestion
    def add(self, x: Object) -> None:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def remove(self, x: Any) -> None:
```suggestion
    def remove(self, x: Object) -> None:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    ) -> Union["DictList", Any]:
```suggestion
        self, i: Union[int, slice, Iterable, Object]
    ) -> Union["DictList", Object]:
```

2022-03-07 09:31 UTC, Midnighter commented on src/cobra/core/dictlist.py
> +    def __setitem__(self, i: Union[slice, int], y: Union[list, Any]) -> None:
```suggestion
    def __setitem__(self, i: Union[slice, int], y: Union[list, Object]) -> None:
```

2022-03-07 15:55 UTC, akaviaLab commented
> Thank you for updating the module. I'm unfortunately not too willing to allow too many `Any` annotations since that doesn't add helpful information. I think, in most cases the `Any` can be replaced with either `Object` or `Union[Object, str]`.

I was a bit confused by get_by_any, which allows multiple types. I wasn't sure what dictlist allows. I can turn everything to Object and then we'll see.

2022-03-07 16:01 UTC, Midnighter commented
When the parameter is `id` it can often be `Object` or `str`.  I can take another careful look when you're done and just commit the changes to your branch.

2022-03-07 16:23 UTC, akaviaLab commented
Yes, please do so. I trust you, and this code is confusing to me.

On Mon, Mar 7, 2022 at 11:02 AM Moritz E. Beber ***@***.***>
wrote:

> When the parameter is id it can often be Object or str. I can take
> another careful look when you're done and just commit the changes to your
> branch.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opencobra/cobrapy/pull/1169#issuecomment-1060849373>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACQYYZUJ2RSLECABDGS5BWLU6YSBNANCNFSM5QB4Q3RQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-12 14:24 UTC, Midnighter approved these changes
Good stuff. We can go over some of the annotations at a later point, should there be issues with them.

2022-03-12 14:24 UTC, merged