Refactor/io sbml
opencobra/cobrapy pull request #1182
Opened 2022-03-13 22:49 UTC by akaviaLab

* [X] description of feature/fix
Updated sbml.py and test_sbml.py to Python 3.6+ including removing future, f-strings, typing. I also made the typing comments in sbml.py to typing annotations.

2022-03-13 22:59 UTC, akaviaLab commented
One question, possibly for @cdiener - Why do we have clip(), and not use something like replace(sid, prefix, 1) or regex?

2022-03-14 17:37 UTC, cdiener requested changes
Looks good. Just a typo.

2022-03-14 17:37 UTC, cdiener commented on src/cobra/io/sbml.py
> +    reaction: "libsbml.Reaction"
Cool, didn't know about this.

2022-03-14 17:37 UTC, cdiener commented on src/cobra/test/test_io/test_sbml.py
> +        Name, original model as read by read_funciton(), test model as read by
typo here, prob should be `read function`

2022-03-14 18:14 UTC, akaviaLab commented
Fixed typo. Still wondering why we use the function _clip(sid: str, prefix: str) -> str: and not something like replace(sid, prefix, 1). Mostly curious.

2022-03-14 18:20 UTC, cdiener commented
> Fixed typo. Still wondering why we use the function _clip(sid: str, prefix: str) -> str: and not something like replace(sid, prefix, 1). Mostly curious.

Because, `str.replace` replaces anywhere in the string but we only want to replace at the beginning of the string here. And str.lstrip only works with single characters.

2022-03-16 22:46 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix:
`prefix: str`

2022-03-16 22:47 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix: str
`prefix: str, optional`

2022-03-16 22:47 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for gene, default "G_".
`... (default "G_").`

2022-03-16 22:48 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for gene, default "G_".
Same as above.

2022-03-16 22:48 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix: str
`prefix: str, optional`

2022-03-16 22:49 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix: str
`prefix: str, optional`

2022-03-16 22:49 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for specie/metabolite, default "M_".
`... (default "M_").`

2022-03-16 22:50 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for specie/metabolite, default "M_".
typo: species

2022-03-16 22:50 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix: str
`prefix: str, optional`

2022-03-16 22:51 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for metabolite, default "M_".
`... (default "M_").`

2022-03-16 22:51 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix: str
`prefix: str, optional`

2022-03-16 22:51 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for reaction, default "R_".
`... (default "R_").`

2022-03-16 22:52 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix: str
`prefix: str, optional`

2022-03-16 22:52 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for reaction, default "R_".
`... (default "R_").`

2022-03-16 22:52 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix: str
`prefix: str, optional`

2022-03-16 22:53 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for group, default "G_".
`... (default "G_").`

2022-03-16 22:53 UTC, synchon commented on src/cobra/io/sbml.py
> +    prefix: str
`prefix: str, optional`

2022-03-16 22:53 UTC, synchon commented on src/cobra/io/sbml.py
> +        Prefix for group, default "G_".
`... (default "G_").`

2022-03-16 22:57 UTC, synchon commented on src/cobra/io/sbml.py
> +        f_replace = dict()
Please prefer literal syntax: `{}`

2022-03-16 23:00 UTC, synchon commented on src/cobra/io/sbml.py
> +    check_model: boolean {True, False}, default True
`bool, optional`

2022-03-16 23:00 UTC, synchon commented on src/cobra/io/sbml.py
> +        Whether to also check some basic model properties such as reaction
`... (default True).`

2022-03-16 23:01 UTC, synchon commented on src/cobra/io/sbml.py
> +    internal_consistency: boolean {True, False}, default True
Please adapt the previous 2 comments.

2022-03-16 23:01 UTC, synchon commented on src/cobra/io/sbml.py
> +    check_units_consistency: boolean {True, False}, default True
Same as above.

2022-03-16 23:01 UTC, synchon commented on src/cobra/io/sbml.py
> +    check_modeling_practice: boolean {True, False}, default True
Same as above.

2022-03-16 23:02 UTC, synchon commented on src/cobra/io/sbml.py
> +        index of error
`... (default None).`

2022-03-16 23:03 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +def test_validate(trial: IOTrial, data_directory: str) -> None:
Please add a Parameters section to the docstring.

2022-03-16 23:03 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    def compare_models(cls, name: str, model1: Model, model2: Model) -> None:
Same as above.

2022-03-16 23:03 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    def extra_comparisons(cls, name: str, model1: Model, model2: Model) -> None:
Same as above.

2022-03-16 23:03 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    def test_read_1(self, io_trial: Tuple[str, Model, Model, Model]) -> None:
Same as above.

2022-03-16 23:04 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    def test_read_2(self, io_trial: Tuple[str, Model, Model, Model]) -> None:
Same as above.

2022-03-16 23:04 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    def test_write_1(self, io_trial: Tuple[str, Model, Model, Model]) -> None:
Same as above.

2022-03-16 23:04 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    def test_write_2(self, io_trial: Tuple[str, Model, Model, Model]) -> None:
Same as above.

2022-03-16 23:04 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +        """Test writing the second model from IOTrail."""
IOTrial is it?

2022-03-16 23:05 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +
The second parameter.

2022-03-16 23:05 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +def test_filehandle(data_directory: str, tmp_path: str) -> None:
Parameters section.

2022-03-16 23:05 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +def test_from_sbml_string(data_directory: str) -> None:
As above.

2022-03-16 23:06 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +def test_model_history(tmp_path: str) -> None:
As above.

2022-03-16 23:07 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +def test_groups(data_directory: str, tmp_path: str) -> None:
Ditto.

2022-03-16 23:07 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +def test_missing_flux_bounds1(data_directory: str) -> None:
Ditto.

2022-03-16 23:07 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
>  def test_missing_flux_bounds2(data_directory):
Parameter type.

2022-03-16 23:08 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    """Test missing flux bounds set to [-INF, INF]."""
Parameters section.

2022-03-16 23:08 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
>      """Test the validation code."""
Ditto.

2022-03-16 23:08 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
>      """Test the validation warnings."""
Ditto.

2022-03-16 23:08 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
>      """Test infinity bound example."""
Ditto.

2022-03-16 23:09 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    assert solution
There needs to be something to assert to.

2022-03-16 23:10 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
>      """Test infinity bound example."""
Parameters section.

2022-03-16 23:10 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    """Test that GPRs are written and read correctly."""
Ditto.

2022-03-16 23:10 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    """Test that NOTES in the RECON 2.2 style are written and read correctly."""
Ditto.

2022-03-16 23:10 UTC, synchon commented on src/cobra/test/test_io/test_sbml.py
> +    """Test that GPRs are written correctly after manual changes."""
Ditto.

2022-03-16 23:11 UTC, synchon requested changes
A few comments. Thank you for the work!

2022-03-16 23:14 UTC, synchon commented
Although a lot a documentation comments, but it is just to help us move faster to enabling `flake8` check. A general comment: please try to maintain the `nummpydoc` documentation conventions.

You have also put a lot of type annotations on variables in the module scope, not really sure if we are doing that. Maybe others can vote for the decision.

2022-03-17 00:11 UTC, akaviaLab commented
> Although a lot a documentation comments, but it is just to help us move faster to enabling `flake8` check. A general comment: please try to maintain the `nummpydoc` documentation conventions.
> 
> You have also put a lot of type annotations on variables in the module scope, not really sure if we are doing that. Maybe others can vote for the decision.

Originally, there were a lot of type annotation comments in this file. Annotation comments are Python 2 compliant, so I updated them to Python 3.

2022-03-17 00:29 UTC, synchon commented
> > Although a lot a documentation comments, but it is just to help us move faster to enabling `flake8` check. A general comment: please try to maintain the `nummpydoc` documentation conventions.
> > You have also put a lot of type annotations on variables in the module scope, not really sure if we are doing that. Maybe others can vote for the decision.
> 
> Originally, there were a lot of type annotation comments in this file. Annotation comments are Python 2 compliant, so I updated them to Python 3.

Yeah I understood why you did those but I don't know if we want those converted now, so left it open for suggestions.

2022-03-18 15:18 UTC, synchon commented
@akaviaLab Let's keep the variable type annotation for now. If needed, we can remove it the future.

2022-03-18 15:19 UTC, synchon approved these changes

2022-03-18 15:20 UTC, synchon commented
I'm okay with the changes. @cdiener If it's okay with you as well, we can merge the PR.

2022-03-21 17:19 UTC, cdiener approved these changes
:+1:

2022-03-21 17:19 UTC, merged