Refactor/core model and test_model.py to Python 3.6+
opencobra/cobrapy pull request #1223
Opened 2022-05-17 14:12 UTC by akaviaLab

* [ ] fix #(issue number)
* [X] description of feature/fix
Upgraded model.py and test_model.py to Python 3.6+
Did some code cleanup of model.py
* [ ] tests added/passed
* [ ] add an entry to the [next release](../release-notes/next-release.md)

2022-05-30 01:21 UTC, akaviaLab commented
@synchon - you're good at reviewing this. Can you please review?

2022-07-06 02:18 UTC, akaviaLab commented
Can anybody please review this? @Midnighter

2022-07-11 09:49 UTC, synchon commented
Hi @akaviaLab! Sorry for not responding, was very busy in the past weeks. I'll do it this week.

2022-07-20 19:37 UTC, akaviaLab commented
@matthiaskoenig @Midnighter @cdiener - can anybody please review this?

2022-07-23 12:00 UTC, synchon commented on .gitignore
>  # Jupyter Notebook
Please remove this line.

2022-07-23 22:26 UTC, synchon requested changes
`tox -e flake8` fails for `test_model.py`. Should be good after addressing the comments.

2022-07-23 22:26 UTC, synchon commented on .gitignore
>  # IPython
Same with this.

2022-07-23 22:26 UTC, synchon commented on .gitignore
>  # Jupyter Notebook
Please remove this.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
>  from cobra.util.util import AutoVivification, format_long_string
The `cobra` imports can be made relative.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def __init__(
Please make the `__init__` as the first method of the class so it's easier to refer the docstring.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        Parameters
The "Parameters" section here should merge with the "Parameters" section in the class docstring. Refer [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring).

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
>      def __setstate__(self, state):
Requires parameter and return type annotation and corresponding documentation. `state` is a dict.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def solver(self) -> "optlang.interface.Model":  # ??I think that's the right type??
That is the correct type AFAIK, also please remove the comment.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        directly and to define additional non-metabolic constraints.
Please add a newline before "Parameters" section.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            The solver to set, which will be checked by check_solver.
Please refer Python objects using backticks (``). "check_solver" -> `check_solver()`

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        _tolerance: float
`_tolerance` variable is not referred inside the method, better to remove it from the docstring.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            self.name = None  # TODO - why is this set as None instead of?? ""
Because the default value of `name` is `None`.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def __getstate__(self) -> dict:
`dict` as return type won't work for Python <= 3.9 . Please make it `Dict` for compatibility.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def description(self) -> str:
I suggest dropping the property. The deprecation notice is there for a long time.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def compartments(self) -> dict:
`dict` -> `Dict`

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def compartments(self, value: dict) -> None:
`dict` -> `Dict`

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            Determine if a boundary reaction permits flux towards creating
This comment should be merged with the one at the beginning.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        def set_active_bound(reaction: Reaction, _bound: float) -> None:
Why is `bound` -> `_bound` needed?

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
>          media_rxns = frozenset(media_rxns)
I suggest replacing the variable shadowing here like so: `media_rxns_frozen = frozenset(media_rxns)` and use `media_rxns_frozen` further.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        # noinspection PyTypeChecker
Why is this required?

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            # noinspection PyTypeChecker
Ditto.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def __add__(self, other_model: "Model") -> "Model":
Can be removed as deprecation warning is issued already.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def __iadd__(self, other_model: "Model") -> "Model":
Ditto.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def copy(self: "Model") -> "Model":
Docstring can be improved with "Returns".

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            # noinspection PyTypeChecker
Please remove if not needed.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +                # noinspection PyProtectedMember
Ditto.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +                    # noinspection PyProtectedMember
Ditto.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +                # noinspection PyProtectedMember
Ditto.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +                [x2.remove_from_model() for x2 in list(x._reaction)]
A good style is to have: `_ = [...]`. Again, not sure if list comprehension is needed.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            [group.remove_members(x) for group in associated_groups]
For style: `_ = [...]`. But, we don't need a list comprehension here if I understand correctly.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        # noinspection PyUnresolvedReferences
Remove if not needed.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            [context(partial(setattr, x, "_model", self)) for x in metabolite_list]
Why do we need list comprehension here?

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def add_reaction(self, reaction: Reaction) -> None:
I suggest removing it as deprecation notice is present already.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def add_reactions(self, reaction_list: "Iterable") -> None:
"Iterable" can be imported outside the `if TYPE_CHECKING: ...` block as Python interpreter already imports it anyway.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def solver(self, value: Union[str, "ModuleType"]) -> None:
"ModuleType" can be imported outside `if TYPE_CHECKING: ...` block.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +                # ?? Maybe this can happen with Reaction.add_metabolites(combine=False)
Please use a relevant comment block like "TODO:" to separate it from other comments.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        def existing_filter(_group: Group) -> bool:
Why the change in variable name?

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        group: Group
Not needed.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            constrained. Default None.
" ... (default None)."

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        reaction: Reaction
Not needed.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +           optimization fails. Default float("nan").
"... (default float("nan"))."

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +           Error message to use if the model optimization did not succeed. Default None.
"... (default None)."

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            the previous direction is used. Default None.
"... (default None)."

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +             optimal. Default False.
Ditto.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
Requires "Returns" section.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        for _dict_list in (self.reactions, self.genes, self.metabolites, self.groups):
Why is this needed?

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            for _entity in _dict_list:
Ditto.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
>          Before introduction of the optlang based problems,
Please change the language assuming optlang-based solvers are the norm.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    def objective(self) -> Union[optlang.Objective, List[Reaction]]:
Adjust assuming optlang-based solvers.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        #TODO - check that it is reset with context.
Remove this comment from the docstring.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        When using a `HistoryManager` context, this attribute can be set
When used in a context, this attribute is set temporarily.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        When using a `HistoryManager` context, this attribute can be set
When used in a context, this attribute is set temporarily.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        fva: Optional[Union["pandas.DataFrame", float]] = None,
"pd.DataFrame"

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    import pandas
import pandas as pd

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +        __exit__ is received. Creates a new context and add it to the stack.
... adds ...

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
```
Parameters
----------
```

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +    ):
Return type annotation.

2022-07-23 22:26 UTC, synchon commented on src/cobra/core/model.py
> +            both. Default 'left'.
```
Returns
-------
```

2022-07-23 22:26 UTC, synchon commented on tests/test_core/test_model.py
> +        model.add_reaction(dummy_reaction)  # noqa:  W6001
I suggest removing `add_reaction()` and thus this would go as well.

2022-07-23 22:26 UTC, synchon commented on tests/test_core/test_model.py
> +def test_add_reaction(model: Model) -> None:
Can be dropped if `add_reaction()` is removed. Same for related tests.

2022-07-23 22:26 UTC, synchon commented on tests/test_core/test_model.py
> +def test_deepcopy_benchmark(model: Model, benchmark: BenchmarkFixture):
Return type annotation.

2022-07-23 22:26 UTC, synchon commented on tests/test_core/test_model.py
> +):
Return type annotation.

2022-07-23 22:26 UTC, synchon commented on tests/test_core/test_model.py
> +def test_optimize(model: Model, solver: str):
Return type annotation.

2022-07-23 22:26 UTC, synchon commented on tests/test_core/test_model.py
> +    with pytest.warns(DeprecationWarning):
Can be removed after dropping `add_reaction()`.

2022-07-25 00:45 UTC, akaviaLab reviewed
Thank you for reviewing this.

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +        Parameters
I think I did this correctly. Please let me know if that's not what you meant.

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +        def set_active_bound(reaction: Reaction, _bound: float) -> None:
Because if I leave it bound, it shadows the bound from 
```
            media_rxns.append(rxn)
            # noinspection PyTypeChecker
            set_active_bound(rxn, bound)
```
And then my linter complains about shadowing from outside scope

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +        # noinspection PyTypeChecker
Because otherwise the linter complains that media_rxns is the wrong type (Object instead of Reaction).
One way to avoid this and many of the problems is adding TypeVar(bound=Object) to dictlist - telling python that DictList will return Object and its derivative classes. See the changes in dictlist.py

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +            # noinspection PyTypeChecker
int vs float because of 
`min(0, ....`
Changed it to min(0.0 and no complaints

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +            # noinspection PyTypeChecker
Not needed with changes to dictlist.py, otherwise needed. Same reason as frozen_media_rxns before

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +            [group.remove_members(x) for group in associated_groups]
Correct. Fixed. Thank you for pointing it out

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +                # noinspection PyProtectedMember
I removed this, but then my IDE complains that _reaction is a private member. Shifted it to # noqa W0212, which is standard pylint error message

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +                [x2.remove_from_model() for x2 in list(x._reaction)]
You're right. List comprehension not needed.

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +            [context(partial(setattr, x, "_model", self)) for x in metabolite_list]
You're right, we don't. I overused list comprehension

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +        def existing_filter(_group: Group) -> bool:
Because my IDE complains about shadowing otherwise

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +            constrained. Default None.
Fixed, except one or two locations where the words "default None" would be on a new line.

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
Done, but short. Not sure what to write here.

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +        for _dict_list in (self.reactions, self.genes, self.metabolites, self.groups):
Informative name, as opposed to one letter variable name.

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +            for _entity in _dict_list:
Ditton

2022-07-25 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
>          Before introduction of the optlang based problems,
I think this is correct. I've left setting objective as it was.

2022-07-26 19:21 UTC, synchon commented on .gitignore
>  # IPython
According to numpydoc, `Parameters` for `__init__`'s docstring are declared in the `Parameters` for the class' docstring. If you check the link in my comment, you will find the reference.

2022-07-26 19:25 UTC, akaviaLab commented
I'm sorry - I can't see this on github, and the email I got points to
.gitignore, so I'm not sure what you're referring to. Do you mean to delete
the docstring from the __init__ constructor?

On Tue, Jul 26, 2022 at 3:21 PM Synchon Mandal ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In .gitignore
> <https://github.com/opencobra/cobrapy/pull/1223#discussion_r930332571>:
>
> > @@ -236,11 +236,8 @@ docs/_build/
>  target/
>
>  # Jupyter Notebook
> -.ipynb_checkpoints
>
>  # IPython
>
> According to numpydoc, Parameters for __init__'s docstring are declared
> in the Parameters for the class' docstring. If you check the link in my
> comment, you will find the reference.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opencobra/cobrapy/pull/1223#discussion_r930332571>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACQYYZRF35GFVBZWBRJAQF3VWA3C3ANCNFSM5WFCTJFQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-26 19:26 UTC, synchon commented on src/cobra/core/model.py
> +        def set_active_bound(reaction: Reaction, _bound: float) -> None:
My opinion is that having parameter names starting with underscore in Python is not a good style. I would have:
```python
for rxn_id, rxn_bound in medium.items():
    ...
    set_active_bound(rxn, rxn_bound)
```

2022-07-26 19:28 UTC, synchon commented
I think there's something weird with GitHub. My comment got deleted.

2022-07-26 19:32 UTC, synchon commented
> I'm sorry - I can't see this on github, and the email I got points to .gitignore, so I'm not sure what you're referring to. Do you mean to delete the docstring from the __init__ constructor?
> […](#)

According to numpydoc, the `Parameters` docstring in `__init__` should be in the class' `Parameters` docstring. Check https://github.com/opencobra/cobrapy/blob/7b1a4ecaa5df90546f760bd100581f7cdf174d89/src/cobra/core/solution.py#L22 for reference.

2022-07-26 19:33 UTC, synchon commented on src/cobra/core/model.py
> +        Parameters
My bad. The other comment got posted in the wrong conversation. See my comment below.

2022-07-26 19:40 UTC, synchon commented on src/cobra/core/model.py
> +        # noinspection PyTypeChecker
I think it's PyCharm that is doing the inspection (you can disable it). I would suggest making changes to `dictlist.py` in a separate PR.

2022-07-26 19:42 UTC, synchon commented on src/cobra/core/model.py
> +                # noinspection PyProtectedMember
Disabling the type checker in PyCharm should do the trick for now. I think adding type hints should be a separate PR.

2022-07-26 19:44 UTC, synchon commented on src/cobra/core/model.py
> +        def existing_filter(_group: Group) -> bool:
Try to not have parameter names starting with underscore. You could change the variable name in the inner scope.

2022-07-26 19:45 UTC, synchon commented on src/cobra/core/model.py
No problem with short docstrings.

2022-07-26 19:46 UTC, synchon commented on src/cobra/core/model.py
> +        for _dict_list in (self.reactions, self.genes, self.metabolites, self.groups):
Okay.

2022-07-26 22:49 UTC, akaviaLab commented
I think I got everything, but the comment threading was confusing.

2022-07-27 22:02 UTC, synchon requested changes
A few more comments. Please run `tox -e flake8` to check for any other issue I might have missed.

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +    id_or_model str, Model
`id_or_model : str or Model`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +
Newline not needed.

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        Default None.
`... as the original model (default None).`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +    def get_metabolite_compartments(self) -> set:
Missed it previous time. The deprecation notice is reasonably old. Can be removed.

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +    def copy(self: "Model") -> "Model":
Forgot about this. Refrain from type annotating `self`.

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
>          destructive : bool
`destructive : bool, optional`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
>          type : str, {"exchange", "demand", "sink"}
`type : {"exchange", "demand", "sink"}`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +            or specifically `model.exchanges` etc (default None).
` ... etc. ...`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +    def add_reactions(self, reaction_list: Iterable) -> None:
More explicit: `reaction_list : List[Reaction]`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
>          reactions : list
The parameter type annotation for `reactions` doesn't match with its docstring.

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
Newline not needed.

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
>          remove_orphans : bool
`remove_orphans : bool, optional`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +            _group: cobra.Group
`new_group : cobra.Group`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +            bool:
`bool`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        self, what: Union[List["CONS_VARS"], Tuple[Union["CONS_VARS"]]], **kwargs
`what : Union[List["CONS_VARS"], Tuple["CONS_VARS", ...]]`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        self, what: Union[List["CONS_VARS"], Tuple[Union["CONS_VARS"]]]
`what : Union[List["CONS_VARS"], Tuple["CONS_VARS", ...]]`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +    ):
`) -> None:`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +            A list of cobra Reactions to add to the solver. This list will be
`A list of cobra.Reaction ...`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +            A list of cobra Metabolites to add to the solver. This list will be
`A list of cobra.Metabolite ...`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        With optlang, the objective is not limited a simple linear summation of
`... limited to a ...`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        value: dict, str, int, Reaction, optlang.interface.Container, Reaction, Basic
The type values should be `or` separated and not `,` separated.

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +            Str of "max" or "min" for direction.
`String ...`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +            If given direction that isn't max or min.
`... direction isn't ...`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        fva: Optional[Union["pd.DataFrame", float]] = None,
Not sure if the linter will allow, but if allowed, use: `solution : Optional["pd.DataFrame", float]`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        self: cobra.Model
`cobra.Model`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
>      def __exit__(self, type, value, traceback):
`... -> None:`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        prefix_existing : string, optional
`prefix_existing : str, optional`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
>              Prefix the reaction identifier in the right that already exist
` ... exist.```

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        objective : {'left', 'right', sum'}
`objective : {"left", "right", "sum"}`

2022-07-27 22:02 UTC, synchon commented on src/cobra/core/model.py
> +        value: {"max", "min}
`value : {"max", "min"}`

2022-07-27 22:02 UTC, synchon commented on tests/test_io/test_json.py
> +    # Filehandle
Separate PR.

2022-07-27 22:02 UTC, synchon commented on tests/test_io/test_json.py
> +    # Test writing with str
Separate PR.

2022-07-27 22:02 UTC, synchon commented on tests/test_io/test_json.py
> +    # FileHandle
Separate PR.

2022-07-27 22:02 UTC, synchon commented on tests/test_io/test_json.py
> +    # str
Separate PR.

2022-07-27 22:02 UTC, synchon commented on tests/test_io/test_json.py
> +    # Path
Separate PR.

2022-07-27 22:02 UTC, synchon commented on tests/test_core/test_model.py
> +    reaction_type: str {"exchange", "demand", "sink"}
`reaction_type : {"exchange", "demand", "sink"}`

2022-07-27 22:02 UTC, synchon commented on tests/test_core/test_model.py
> +    reaction_type: str {"exchange", "demand", "sink"}
`reaction_type : {"exchange", "demand", "sink"}`

2022-07-27 22:02 UTC, synchon commented on tests/test_core/test_model.py
> +    reaction_type: str {"exchange", "demand", "sink"}
`reaction_type : {"exchange", "demand", "sink"}`

2022-07-27 22:02 UTC, synchon commented on tests/test_core/test_model.py
>              solver_dict[solver].create_problem(large_model)
`solver_dict` is unavailable in this module. You will get the error once you run `tox -e flake8`.

2022-07-27 22:02 UTC, synchon commented on tests/test_core/test_model.py
>              solver_dict[solver].create_problem(model)
`solver_dict` is unavailable in this module.

2022-07-27 22:02 UTC, synchon commented on tests/test_core/test_model.py
> +        Solver to use. Parametized using stable_optlang defined above.
`... . Parametrized using 'optlang_solvers' defined above.`

2022-07-27 23:55 UTC, akaviaLab commented on src/cobra/core/model.py
> +    def get_metabolite_compartments(self) -> set:
Already removed

2022-07-28 00:45 UTC, akaviaLab reviewed
Fixed. solver_dict is something I don't think should be removed, because that would change functionality.

2022-07-28 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
> +    def add_reactions(self, reaction_list: Iterable) -> None:
Changed it to Iterable[Reaction]

2022-07-28 00:45 UTC, akaviaLab commented on src/cobra/core/model.py
>              Prefix the reaction identifier in the right that already exist
This doesn't seem right, since the sentence is
"...already exist in the left..."

2022-07-28 00:45 UTC, akaviaLab commented on tests/test_core/test_model.py
>              solver_dict[solver].create_problem(model)
I know it isn't available, but it works, so it must be initialized somehow when running the tests. If it wasn't available at all, the tests would refuse to run or fail. @Midnighter - any comments?

2022-07-28 00:45 UTC, akaviaLab commented on tests/test_io/test_json.py
> +    # Path
This isn't a change in the functionality, just a minor comment to make it easier to understand. Does it need to be in a different PR?

2022-07-28 00:45 UTC, akaviaLab commented on tests/test_io/test_json.py
> +    # Filehandle
as above

2022-08-01 20:52 UTC, akaviaLab commented
ping @synchon

2022-08-04 20:37 UTC, synchon commented
@akaviaLab Sorry, I'll take a look by weekend.

2022-08-07 11:21 UTC, synchon commented on src/cobra/core/model.py
>              Prefix the reaction identifier in the right that already exist
My bad, the diff panel made it confusing. It's ok as it is.

2022-08-07 11:24 UTC, synchon commented on tests/test_io/test_json.py
> +    # Path
It's better to keep them separate as it's easy to track in the future and also stays true to what the PR does.

2022-08-07 11:42 UTC, synchon commented on tests/test_core/test_model.py
>              solver_dict[solver].create_problem(model)
After a bit of time machine action, you can see the code was introduced in #307 when `optlang`-based solvers were not the norm. So, then one needed to check if the model had a solver attached to it or not. Now, GLPK is always available so the check will never happen. You can run and check it. As it's a parametrized benchmark, we can do something like:
```python
model.solver = solver
```
to benchmark different solvers as done in `test_optimize()`. So, my suggestion would be to go for this and replace `stable_optlang` with `optlang_solvers` or let `stable_optlang` be as it is.

You can also see some similar check in `test_core_reaction.py` and these are remnants of the pre-`optlang` times.

2022-08-07 11:58 UTC, synchon requested changes

2022-08-07 11:58 UTC, synchon commented on src/cobra/core/model.py
> +    id_or_model: str or Model
`id_or_model : str or Model, optional`

2022-08-07 11:58 UTC, synchon commented on src/cobra/core/model.py
> +        self, id_or_model: Union[str, "Model"] = None, name: Optional[str] = None
`... , id_or_model: Union[str, "Model", None] = None, ...`

2022-08-07 20:29 UTC, akaviaLab commented on tests/test_core/test_model.py
>              solver_dict[solver].create_problem(model)
I'm guessing you don't want me to fix test_core_reaction()
The ones in test_model.py are fixed.

2022-08-09 22:26 UTC, synchon approved these changes

2022-08-09 22:26 UTC, synchon commented
Everything looks good. I'll push a couple of cleanup commits and should be good to go. Thanks for your effort @akaviaLab !

2022-08-09 22:54 UTC, synchon commented
@akaviaLab Okay seems to be a hassle to push my commits to your forked repo. I'll merge this and push the changes in a separate PR. Cheers!

2022-08-09 22:55 UTC, merged