Store the compartment for created metabolites
opencobra/cobrapy pull request #1420
Opened 2024-12-13 02:55 UTC by oxinabox

* [x] fix #1418 
* [x] desc: store compartment when metabolite created
* [x] tests added/passed
* [ ] add an entry to the [next release](../release-notes/next-release.md)

2025-01-07 09:56 UTC, cdiener requested changes
Looks good. The linter was complaining about a docstring.

2025-01-07 09:56 UTC, cdiener commented on tests/test_core/test_core_reaction.py
> +    # https://github.com/opencobra/cobrapy/issues/1418
```suggestion
    """Test that metabolites are created in the correct compartment."""
    # https://github.com/opencobra/cobrapy/issues/1418
```

2025-01-07 12:04 UTC, cdiener commented
There was another small issue with the logic in `Reaction.build_reaction_from_string`. Let me know if the changes are fine with you.

2025-01-07 12:37 UTC, oxinabox commented
lgtm

2025-01-08 12:32 UTC, cdiener approved these changes

2025-01-08 12:32 UTC, merged