refactor: make `cobra.util` Python 3.6+
opencobra/cobrapy pull request #975
Opened 2020-07-25 09:43 UTC by synchon

This PR addresses a part of #972 and makes `cobra.util` along with its tests compatible with Python 3.6+ only.

2020-07-25 10:06 UTC, matthiaskoenig requested changes

2020-07-25 10:06 UTC, matthiaskoenig commented on src/cobra/test/test_util/test_array.py
Remove the 
``` 
try:
    import scipy
except ImportError:
    scipy = None
```

Not used here, unnecessary.

2020-07-25 10:06 UTC, matthiaskoenig commented on src/cobra/test/test_util/test_solver.py
Replace string concatenation with fstrings:
``` 
optlang_solvers = ["optlang-" + s for s in stable_optlang if s in su.solvers]
```
```
optlang_solvers = [f"optlang-{s}" for s in stable_optlang if s in su.solvers]
``
Much clearer to read and faster.

2020-07-25 10:08 UTC, matthiaskoenig commented
Please add type annotations to the function signatures whenever possible (i.e. where the types are clear). 
This allows automatic checking of the code base and also provides many helpers to users of cobrapy.
Type annotations are one of the best >python3.6 features and libraries should make use of them.

2020-07-25 10:33 UTC, synchon commented on src/cobra/test/test_util/test_array.py
It's being used for:
```python
@pytest.mark.skipif(not scipy, reason="Sparse array methods require scipy")
```

2020-07-25 10:39 UTC, synchon commented
Yes I agree and strongly support type annotations. I thought we could tackle it in a separate PR but doing it here is not bad either.

2020-07-25 10:47 UTC, matthiaskoenig commented
I would do all the python3.6 changes at once. I.e.

- fix imports
- remove object from class definition
- remove six usage
- remove future imports
- remove encodings
- use fstrings when possible
- type annotations

Otherwise we will go over all code 3 times. Let's do this in a single round if possible.

2020-07-25 10:53 UTC, synchon commented
I propose to capitalize variable names in module's global scope, for example:
```python
qp_solvers = ["cplex", "gurobi"]
```
to
```python
QP_SOLVERS = ["cplex", "gurobi"]
```
I feel this improves readability and also indicates that it's in the global scope.

2020-07-26 13:12 UTC, Midnighter commented
@synchon to me it depends on the intention of the global (module-level) variable. I would use uppercase when it is intended as a constant and lowercase when it is used as an object.

I think I introduced it myself some time ago but nowadays I would, for example, use lowercase for the logger object.

```py
logger = logging.getLogger(__name__)
```

Your example seems like a constant so I think uppercase is the right way to go. Unless a list is required the constant aspect could be made even stronger by:

```py
QP_SOLVERS = frozenset(["cplex", "gurobi"])
```

2020-07-26 13:13 UTC, Midnighter commented
@matthiaskoenig I have lifted your comment into #972.

2020-07-26 13:20 UTC, Midnighter commented
@synchon I would really go module by module rather than tackling a whole sub-package. There are more things that we can tackle here in addition to what Matthias mentioned. New code should be formatted with `isort` and `black`, and I would like us to slowly move towards passing `flake8`. That especially means that we need to give the docstrings some love. This is currently not part of the pipeline because there are too many errors but locally you can run `tox -e flake8 path/to/module.py` to check. When writing docstrings please follow https://numpydoc.readthedocs.io/en/latest/format.html

I will add this to the issue, too.

2020-07-26 13:33 UTC, Midnighter commented on src/cobra/test/test_util/test_array.py
I would use https://docs.pytest.org/en/stable/skipping.html#skipping-on-a-missing-import-dependency

2020-07-27 06:44 UTC, synchon commented
> I would use uppercase when it is intended as a constant and lowercase when it is used as an object.

Yes exactly. That's what I use for my personal projects as well.

2020-07-27 06:52 UTC, synchon commented
@Midnighter For the further commits, I'll go atomic at the module level. I'm using `isort` and `black` currently, I'll also add `flake8` for local development. I'm working on the docstrings as well.

2020-07-31 22:11 UTC, Midnighter commented
@synchon if you can fix the scipy import check in the tests I'm actually tempted to pull in these changes now. I think it will  be easier to create separate quick PRs for each module rather than adding to this one.

2020-08-01 06:09 UTC, synchon commented
@Midnighter sorry, I was a bit caught up with work through the week, but I'll push the change for scipy import check. I have local changes for the `cobra.util` subpackage and I'll push them in separate PRs.

2020-08-01 12:09 UTC, synchon commented
The CI is failing due to #978 but it improves the scipy import check.

2020-08-06 20:21 UTC, Midnighter approved these changes
Pulling this in for now. We know that the tests fail for other reasons. Thank you for your work Synchon.

2020-08-06 20:22 UTC, merged